### PR TITLE
fix #1963 - Mentions are visually incorrect when used in message replies

### LINKED ISSUE #1963: Mentions are visually incorrect when used in message replies
**Describe the bug**
A message reply typically starts with the > character. Unfortunately, that the is the XML begin tag character. This causes filterXSS to escape it into *& lt;* This invalidates the start values of all references in the message and causes them to to be displayed incorrectly like this

image

**To Reproduce**
Type any message with one or more mentions and start it with > character

**Expected behavior**
The > character at the start of a message should be ignored and left unescaped as it cannot be part of any well-formed XML

**Solution**
Override the escapeHtml function in filterXSS like this
```
'escapeHtml': function (html) {
  if (html.startsWith('>'))
    return '>' + html.substring(1).replace(/</g, '&lt;').replace(/>/g, '&gt;');
  else
    return html.replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

```

### PR DESCRIPTION
**Pull request by deleolajide**
Third attempt at fixing this by modifying addMentionsMarkup. I now adjust reference start and end based on the count for prior occurences of the &_lt; and &_gt; characters.

I really dislike the start/end value system used in the references instead of a simple markdown like the colon delimters used with emojis. It reminds me of fixed length records used in very old school COBOL programming.

### CODE REVIEW

**Comment by jcbrand** [comment]
I've been thinking a bit about referencing rich elements in text messages. 

XEP-394 also uses start/end indicators for rich elements, so this is a problem that needs solving generally and not just for a particular use-case.

I think this should be fixed as part of the lit-html rewrite of how messages are rendered, that the general problem of referencing positions in a message is handled and that this is done in a way so that people can add message rendering "middleware" to add new capabilities to what can be rendered in a message.

I'm laying the groundwork for using lit-html for rendering message and will hopefully be able to start working on that in the next few weeks.

Until then, I don't think it makes sense to merge this PR yet.

**Comment by deleolajide** [comment]
> Until then, I don't think it makes sense to merge this PR yet.

I appreciate your efforts towards refactoring text messages for rich elements using lit-html. However, I have an immediate usability issue to address. StartinBlox users make heavy use of message replies with mentions and have made this an [**issue that has to be fixed**](https://git.startinblox.com/components/sib-chat/issues/132). They can't wait for Converse 7 for this.

I have spent a bit of time and effort trying to find a fix with mimium impact that passes all the converse tests as you requested in your first comment. 

By asking me to throw all that away, you are sending me mixed messages about how to contribute to Converse development. I can't fix this from a plugin and do not want to create or maintain a fork for StartinBlox. Please review my logic for improvment and reconsider for an immediate merge. Thank you.

**Comment by jcbrand** [comment]
> StartinBlox users make heavy use of message replies with mentions and have made this an issue that has to be fixed. They can't wait for Converse 7 for this.

The reason I don't want to merge this to trunk is because I think the chance that this change will ever get released is very low.

If your users can't wait for Converse 7, then how is merging this to trunk going to solve anything for you? AFAIK your users aren't using trunk in any case, but instead use a patched version of Converse 6, right?

> I have invested a bit of time and effort trying to find a fix with mimium impact that passes all the converse tests as you requested in your first comment.

Asking that all tests pass isn't some kind of extra burden that I placed on you for a particular PR, it's pretty much the most basic requirement for *any* PR to be mergeable (unless it's clear to me that tests are failing due to some other reason not related to the PR).

While we're on the topic of tests, I've often asked other people to first write tests specific to their PR before merging and when fixing a bug it's generally expected to write a regression test to check that the bug is fixed and to ensure that it doesn't happen again.

In the interest of good engineering practice and fairness to all contributors, I'd like you to also write tests when making PRs. When someone is a new contributor who doesn't know the codebase very well, then one could perhaps let the tests requirement slide, but you're a veteran by now.

> By asking me to throw all that away, you are sending me mixed messages about how to contribute to Converse development.

I didn't ask that you throw away this PR, but I'm also not obligated to merge a PR just because it took someone a lot of effort to contribute it.

I'm sorry if you feel like you're getting mixed messages, that's not my intention. I, and others, appreciate your contributions. However, I also reasonably expect contributions to conform to a minimum level of quality (e.g. tests being green) and relevance to the roadmap (e.g. not in conflict with future planned changes).

> I can't fix this from a plugin and do not want to create or maintain a fork for StartinBlox

The 6.x.x branch (which AFAIK you're using) is already a fork and this PR will likely never be released as part of Converse 7.

So as a compromise, you can make this PR against the 6.x.x branch, add a regression test, and then I'll merge it there.

**Comment by jcbrand** [comment]
> So as a compromise, you can make this PR against the 6.x.x branch, add a regression test, and then I'll merge it there.

I realise now that having this change together with a regression test in trunk will ensure that when I do eventually rewrite message rendering to use lit-html, that this bug doesn't reappear.

So if you write a regression test, then I think there is a good enough reason to have this in trunk and not just the 6.x.x branch.

So please add a regression test to this PR and I'll merge to trunk.

**Comment by deleolajide** [comment]
> So please add a regression test to this PR and I'll merge to trunk.

Thank you. I have always added a test for new features, but you have a point about bug fixes that I did not consider. Adding the the mssing test that would have prevented the bug in the first place is also part of fixing the bug :-)

>I didn't ask that you throw away this PR, but I'm also not obligated to merge a PR just because it took someone a lot of effort to contribute it.

I apprecate that, but if you had pointed out in your first comment that "_don't think it makes sense to merge this PR yet_" into master, then I would have closed the PR and concentrated on a fork. 

A question for you. 

Should PRs that make changes to message rendering before you refactor with lit-html target the converse-6.xx branch or the master because of the regression tests?

**Comment by jcbrand** [comment]
> Should future PRs that make changes to message rendering before you refactor with lit-html target the converse-6.xx branch or the master because of the regression tests?

The answer depends on how far trunk and 6.x.x have diverged. If they diverge too much, you'll have to make a decision about which branch you want to use.

If they haven't yet diverged much (when it comes to message rendering) then based on this discussion, if it's a bugfix with a regression test, then it should probably go into master with a cherry-pick into 6.x.x.

**Pull request merged**
