### PR TITLE
Allow to disable the user profile modal

### PR DESCRIPTION
**Pull request by reda-alaoui**
Thanks for making a pull request to converse.js!

Before submitting your request, please make sure the following conditions are met:

- [x] Add a changelog entry for your change in `CHANGES.md`
- [x] When adding a configuration variable, please make sure to
      document it in `docs/source/configuration.rst`
- [ ] Please add a test for your change. Tests can be run in the commandline
      with `make check` or you can run them in the browser by running `make serve`
      and then opening `http://localhost:8000/tests.html`.

### CODE REVIEW

**Comment by jcbrand** [comment]
There's a better way to disable the profile, just add `converse-profile` to the [blacklisted_plugins](https://conversejs.org/docs/html/configuration.html#blacklisted-plugins) setting.

**Comment by reda-alaoui** [comment]
@jcbrand , I tried this first.
When I do this, the whole control box is blank.

**Comment by jcbrand** [comment]
>  When I blacklist converse-profile, the whole control box is blank.

Then that should be fixed instead of adding another config variable.

**Comment by reda-alaoui** [comment]
@jcbrand , `converse-profile` is responsible for displaying the whole profile_view.html.
For my need, I don't want to hide the whole profile view (e.g I want to keep the avatar display) , I just want to prevent the detailed profile modal to be opened by the end user because he is not allowed to modify his profile information in my application.
I think blacklisting `converse-profile` is not what I need.

**Pull request closed without merging**
