### PR TITLE
Display MAM logs before joining the MUC

### PR DESCRIPTION
**Pull request by linkmauve**
The location of the nickname prompt has been moved to replace the message input, like in most Slack clones.

This allows visitors to view MAM logs before deciding whether they want to join the MUC or not.

### CODE REVIEW

**Comment by linkmauve** [comment]
This should be a “Join groupchat” button, which opens the nickname modal.

**Comment by jcbrand** [comment]
> This should be a “Join groupchat” button, which opens the nickname modal.

Otherwise confused outside think it's the message input and type their first message in there

**Comment by poVoq** [comment]
Any chance this could still be merged?
The example over here where it is implemented is quite nice:
https://wikisuite.chat/XMPP

**Comment by jcbrand** [comment]
> Any chance this could still be merged?

Not as is, too much has changed in the meantime.

**Comment by jcbrand** [comment]
Merged manually and made some further improvements and fixes.

**Comment by alexanderadam** [comment]
You are awesome @jcbrand! Thank you so much! 🙏

**Comment by jcbrand** [comment]
You're welcome :)

**Comment by jcbrand** [comment]
Thanks also to @linkmauve for making the original PR.

**Pull request closed without merging**
