### PR TITLE
Small pt_BR corrections

### PR DESCRIPTION
**Pull request by brneor**
Just found some small orthographic errors while adding converse.js to a system I'm working on and fixed it.

### CODE REVIEW

**Comment by licaon-kter** [comment]
Can you use the translation portal please?

**Comment by brneor** [comment]
Of course! Can you link it? Couldn't find it anywhere.

**Comment by jcbrand** [comment]
Thanks @brneor, I've merged your changes. For future reference, you can make translations here:
https://hosted.weblate.org/projects/conversejs/translations

**Comment by brneor** [comment]
@jcbrand my pleasure! Thank you for the link, I'll have a look from time to time and help with the translation.

**Pull request merged**
