### PR TITLE
add config option 'reload_on_disconnect'

### PR DESCRIPTION
**Pull request by ChaosKid42**
This is supposed to provide a solution for https://github.com/conversejs/converse.js/issues/1735.

### CODE REVIEW

**Comment by jcbrand** [comment]
As you're well aware, this is a hack :)

I think we should rather try to fix the underlying problem (not that I currently know what it is).

**Comment by ChaosKid42** [comment]
Yes. It's a hack. So from my point of view it would be ok if you close this PR. It can still be referenced in case any user cares to use this hack until the real solution is available.

Do you have any idea what the underlying problem could be? I would like to investigate this further but I can't due to lack of ideas where to look :-)

**Comment by jcbrand** [comment]
I've commented on the ticket.

**Comment by jcbrand** [comment]
#1735 has now been fixed.

**Pull request closed without merging**
