### PR TITLE
Shadow dom: TypeError: Cannot read property 'parentElement' of null caused by MinimizedChatsToggleView

### PR DESCRIPTION
**Pull request by reda-alaoui**
Thanks for making a pull request to converse.js!

Before submitting your request, please make sure the following conditions are met:

- [x] Add a changelog entry for your change in `CHANGES.md`
- [ ] Please add a test for your change. Tests can be run in the commandline
      with `make check` or you can run them in the browser by running `make serve`
      and then opening `http://localhost:8000/tests.html`.

### CODE REVIEW

**Comment by reda-alaoui** [comment]
For the test, please tell me what form it should have and where I should put it.

**Comment by jcbrand** [comment]
Thanks for your pull request.

Can you please explain more about the problem and why this fixes it?
Why is this error happening for this View, but not all the others?

I've used Converse.js in a web component with shadow DOM before and didn't have this problem.

It looks to me like Converse tries to get  `#toggle-minimized-chats` from the parent (light) DOM? Instead of the shadow DOM which it is actually in.

**Comment by reda-alaoui** [comment]
I had this issue with Chrome 75 and conversejs 4.2.0.

> It looks to me like Converse tries to get #toggle-minimized-chats from the parent (light) DOM? Instead of the shadow DOM which it is actually in.

Yes indeed. I think this is the only converse.js module doing this. The others retrieve/create their element themselves by using the root element.

**Comment by jcbrand** [comment]
Ok, I think I know why... it's the only view that specifies `el: #....`, so it's the only View that tells Backbone to go look for an element in the DOM that represents it.

I don't think a test is necessary.

Thanks again.

**Pull request merged**
